<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>QTM 385 - Experimental Methods</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="09-assignment_files/libs/clipboard/clipboard.min.js"></script>
<script src="09-assignment_files/libs/quarto-html/quarto.js"></script>
<script src="09-assignment_files/libs/quarto-html/popper.min.js"></script>
<script src="09-assignment_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="09-assignment_files/libs/quarto-html/anchor.min.js"></script>
<link href="09-assignment_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="09-assignment_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="09-assignment_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="09-assignment_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="09-assignment_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">QTM 385 - Experimental Methods</h1>
<p class="subtitle lead">Assignment 09</p>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="instructions" class="level1">
<h1>Instructions</h1>
<p>This assignment deals with causal inference with heterogeneous effects. The topic is discussed in chapter 09 of the textbook. If you have any questions about the assignment, feel free to email me at <a href="mailto:danilo.freire@emory.edu" class="email">danilo.freire@emory.edu</a>.</p>
<p>Good luck!</p>
</section>
<section id="questions" class="level1">
<h1>Questions</h1>
<ol type="1">
<li>Define the following concepts and answer the questions:</li>
</ol>
<ol type="a">
<li><p>Define CATE. Is a Complier average causal effect (CACE) an example of a CATE? CATE, or Conditional Average Treatment Effect, is the average effect of a treatment for a specific subgroup defined by covariates (e.g., age, income). It helps understand how treatment effects vary across different segments of a population. CACE is not a CATE; rather, it estimates the average treatment effect for compliers in an instrumental variables setting, which is a subgroup based on treatment adherence rather than pre-treatment covariates.</p></li>
<li><p>What is an interaction effect? An interaction effect occurs when the effect of one independent variable on the outcome depends on the level of another variable. This means that the variables do not have purely additive effects, but instead modify each other’s impact. Interaction effects are key to understanding heterogeneity in causal relationships.</p></li>
<li><p>Describe the multiple comparisons problem and the Bonferroni correction. What other ways are there to correct the multiple comparisons problem? (Feel free to use other reference materials to answer this question) The multiple comparisons problem arises when performing many statistical tests, increasing the chance of finding a significant result just by chance (Type I error). The Bonferroni correction addresses this by dividing the significance level (e.g., 0.05) by the number of comparisons to keep the overall error rate low. Other correction methods include the Holm-Bonferroni method, False Discovery Rate (FDR) control like the Benjamini-Hochberg procedure, and permutation-based adjustments.</p></li>
</ol>
<ol start="2" type="1">
<li>Suppose that a researcher compares the CATE among two subgroups, men and women. Among men (<span class="math inline">\(N = 100\)</span>), the ATE is estimated to be <span class="math inline">\(8.0\)</span> with a standard error of <span class="math inline">\(3.0\)</span>, which is significant at <span class="math inline">\(p &lt; 0.05\)</span>. Among women (<span class="math inline">\(N = 25\)</span>), the CATE is estimated to be <span class="math inline">\(7.0\)</span> with an estimated standard error of <span class="math inline">\(6.0\)</span>, which is not significant, even at the 10% significance level. Critically evaluate the researcher’s claim that “<em>the treatment only works for men; for women, the effect is statistically indistinguishable from zero</em>”. In formulating your answer, address the distinction between testing whether a single CATE is different from zero and testing whether two CATEs are different from each other. The researcher’s claim that “the treatment only works for men; for women, the effect is statistically indistinguishable from zero” reflects a misinterpretation of statistical inference and subgroup comparisons.</li>
</ol>
<p>While it is true that the treatment effect is statistically significant for men (ATE = 8.0, SE = 3.0, p &lt; 0.05) and not for women (CATE = 7.0, SE = 6.0, not significant), this does not imply a statistically significant difference between the two groups. Statistical significance within a group does not imply a statistically significant difference between groups. To assess whether the treatment effect differs by gender, the researcher would need to formally test the interaction effect (i.e., whether the difference between 8.0 and 7.0 is significantly different from zero, accounting for the pooled variance), and in this case, the large standard error for women suggests the difference likely isn’t significant.</p>
<p>In short: “Significant vs.&nbsp;not significant” is not the same as “significantly different”, and concluding treatment heterogeneity without testing the interaction is statistically invalid.</p>
<ol start="3" type="1">
<li>For questions 3 to 5, consider the following table and data. In their 2004 study of racial discrimination in employment markets, Bertrand and Mullainathan sent resumes with varying characteristics to firms advertising job openings. Some firms were sent resumes with putative African American names, while other firms received resumes with putatively Caucasian names. The researchers also varied other attributes of the resume, such as whether the resume was judged to be of high or low quality (based on labor market experience, career profile, gaps in employment, and skills listed). The table below shows the rate at which applicants were called back by employers, by the city in which the experiment took place and by the randomly assigned attributes of their applications.</li>
</ol>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">City</th>
<th style="text-align: left;">Resume Quality</th>
<th style="text-align: left;">Race</th>
<th style="text-align: left;">% Received call</th>
<th style="text-align: left;">(N)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Boston</td>
<td style="text-align: left;">Low-quality</td>
<td style="text-align: left;">Black</td>
<td style="text-align: left;">7.01</td>
<td style="text-align: left;">(542)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Boston</td>
<td style="text-align: left;">Low-quality</td>
<td style="text-align: left;">White</td>
<td style="text-align: left;">10.15</td>
<td style="text-align: left;">(542)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Boston</td>
<td style="text-align: left;">High-quality</td>
<td style="text-align: left;">Black</td>
<td style="text-align: left;">8.50</td>
<td style="text-align: left;">(541)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Boston</td>
<td style="text-align: left;">High-quality</td>
<td style="text-align: left;">White</td>
<td style="text-align: left;">13.12</td>
<td style="text-align: left;">(541)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Chicago</td>
<td style="text-align: left;">Low-quality</td>
<td style="text-align: left;">Black</td>
<td style="text-align: left;">5.52</td>
<td style="text-align: left;">(670)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Chicago</td>
<td style="text-align: left;">Low-quality</td>
<td style="text-align: left;">White</td>
<td style="text-align: left;">7.16</td>
<td style="text-align: left;">(670)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Chicago</td>
<td style="text-align: left;">High-quality</td>
<td style="text-align: left;">Black</td>
<td style="text-align: left;">5.28</td>
<td style="text-align: left;">(682)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Chicago</td>
<td style="text-align: left;">High-quality</td>
<td style="text-align: left;">White</td>
<td style="text-align: left;">8.94</td>
<td style="text-align: left;">(682)</td>
</tr>
</tbody>
</table>
<p>For each city, interpret the apparent treatment effects of a black name and a low-quality resume on the probability of receiving a follow-up call. In Boston, having a Black-sounding name significantly reduced the likelihood of receiving a callback. Among low-quality resumes, White applicants received callbacks at a rate of 10.15%, while Black applicants received only 7.01%, reflecting a gap of 3.14 percentage points. This racial gap widened for high-quality resumes, where callback rates were 13.12% for White applicants and 8.50% for Black applicants—a difference of 4.62 percentage points. In terms of resume quality, higher-quality resumes increased callback rates for both racial groups, but the benefit was greater for White applicants. White applicants saw a 2.97 percentage point increase in callbacks when moving from low- to high-quality resumes, compared to just 1.49 percentage points for Black applicants.</p>
<p>In Chicago, a similar pattern of racial discrimination emerges, though the differences are slightly smaller. Among low-quality resumes, White applicants had a callback rate of 7.16% compared to 5.52% for Black applicants, yielding a gap of 1.64 percentage points. For high-quality resumes, the callback rate was 8.94% for White applicants and 5.28% for Black applicants—a 3.66 percentage point gap. Interestingly, resume quality had little to no positive effect for Black applicants in Chicago. In fact, Black applicants with high-quality resumes received slightly fewer callbacks (5.28%) than those with low-quality resumes (5.52%), a difference likely due to random variation. Meanwhile, White applicants saw a clear benefit from better resumes, with a 1.78 percentage point increase in callback rates.</p>
<p>Taken together, these patterns suggest that Black-sounding names were consistently penalized in the hiring process in both cities, and that improvements in resume quality disproportionately benefited White applicants. The results underscore how racial bias can persist even in the presence of strong qualifications, particularly in the case of high-quality resumes where the racial callback gap actually widened.</p>
<ol start="4" type="1">
<li>Propose a regression model that assesses the effects of the treatments, interaction between them, and interactions between the treatments and the covariate, city, where city is coded 1 for subjects in Boston and 0 for Chicago. Define your variables clearly. To evaluate how race, resume quality, and city affect the likelihood of receiving a callback, we can use a regression model that includes both main effects and interaction terms. The outcome variable is whether an applicant received a callback (<em>Callback</em>), coded as 1 if they did and 0 otherwise. The key explanatory variables are: <em>Black</em>, a binary variable equal to 1 if the applicant has a Black-sounding name (0 if White); <em>HighQual</em>, a binary variable equal to 1 if the resume is high quality (0 if low quality); and <em>Boston</em>, a binary covariate equal to 1 if the job application was sent to a Boston employer (0 if Chicago).</li>
</ol>
<p>The model includes not only these three main effects, but also their interactions to assess whether the effects of race and resume quality vary by city. Specifically, the model includes interaction terms for <em>Black × HighQual</em>, <em>Black × Boston</em>, <em>HighQual × Boston</em>, and a three-way interaction <em>Black × HighQual × Boston</em>. These terms allow us to estimate how the combination of being Black and having a high-quality resume affects outcomes differently in Boston versus Chicago.</p>
<p>This regression framework enables a nuanced analysis of discrimination in hiring by testing whether racial disparities in callback rates are influenced by resume quality and whether these patterns differ between cities. For example, the coefficient on <em>Black</em> reflects the effect of having a Black-sounding name in Chicago for applicants with low-quality resumes, while the interaction terms reveal whether this effect changes in Boston or for higher-quality resumes. By including these interactions, the model captures both the direct treatment effects and the contextual factors that may moderate them.</p>
<ol start="5" type="1">
<li>Estimate the parameters in your regression model and interpret the results. (This can be done by hand based on the percentages given in the table.) Based on the callback rates in the table, we can manually estimate the parameters of the proposed regression model by computing differences in means across the eight groups (defined by combinations of city, race, and resume quality). We’ll treat Chicago, low-quality, White-sounding resumes as the reference group. This group has a callback rate of 7.16%, so our intercept (β₀) is 0.0716.</li>
</ol>
<p>Next, we estimate the effect of a Black-sounding name in Chicago with a low-quality resume (β₁). In this condition, the callback rate is 5.52%, so the effect of being Black (compared to White) is 0.0552 − 0.0716 = −0.0164. For resume quality (β₂), we compare high- and low-quality resumes for White applicants in Chicago: 8.94% − 7.16% = +0.0178. The main effect of being in Boston (β₃) is estimated by comparing the White, low-quality group in Boston (10.15%) to the same group in Chicago (7.16%): 10.15% − 7.16% = +0.0299.</p>
<p>To estimate the two-way interaction between being Black and having a high-quality resume in Chicago (β₄), we compare the difference in callback rates for Black applicants by resume quality: 5.28% (high) − 5.52% (low) = −0.0024, and subtract the main effect of resume quality for Whites (+0.0178), yielding −0.0202. This suggests that Black applicants in Chicago did not benefit from higher resume quality. The interaction between race and city (β₅) is the difference in the race gap between Boston and Chicago for low-quality resumes: (7.01 − 10.15) − (5.52 − 7.16) = −3.14% − (−1.64%) = −0.0150. This indicates the racial gap is 1.5 percentage points worse in Boston. Similarly, the interaction between resume quality and city (β₆) for White applicants is (13.12 − 10.15) − (8.94 − 7.16) = 2.97% − 1.78% = +0.0119, showing that resume improvements were slightly more rewarded in Boston. Finally, the three-way interaction (β₇) can be estimated by comparing the differential quality boost for Black applicants in Boston versus Chicago: (8.50 − 7.01) − (5.28 − 5.52) = 1.49% − (−0.24%) = +0.0173, suggesting a modestly better return to resume quality for Black applicants in Boston, though still small.</p>
<p>In sum, the regression estimates reveal consistent racial disparities in callback rates, with Black applicants receiving fewer callbacks overall, and especially in Boston. Resume quality had a positive impact for White applicants in both cities, but offered little to no advantage for Black applicants, particularly in Chicago. The interaction effects suggest that resume quality reinforces inequality, providing greater benefits to White applicants and doing little to offset racial bias in hiring.</p>
<ol start="6" type="1">
<li><a href="https://doi.org/10.1111/j.1559-1816.1996.tb01847.x">Rind and Bordia</a> studied the tipping behaviour of lunchtime patrons of an “upscale Philadelphia restaurant” who were randomly assigned to four experimental groups. One factor was server sex (male or female), and a second factor was whether the server draws a “happy face” on the back of the bill presented to customers. Download the data located at <a href="https://github.com/danilofreire/qtm385/blob/main/assignments/09-assignment/Rind_Bordia_JASP_1996.csv" class="uri">https://github.com/danilofreire/qtm385/blob/main/assignments/09-assignment/Rind_Bordia_JASP_1996.csv</a> and read the data into R.</li>
</ol>
<p>Suppose you ignored the sex of the server and simply analysed whether the happy face treatment has heterogeneous effects. Use randomisation inference to test whether <span class="math inline">\(\text{Var}(\tau_i) = 0\)</span> by testing whether <span class="math inline">\(\text{Var}(Y_i(1)) = \text{Var}(Y_i(0))\)</span>. Construct the full schedule of potential outcomes by assuming that the treatment effect is equal to the observed difference-in-means between <span class="math inline">\(Y_i(1)\)</span> and <span class="math inline">\(Y_i(0)\)</span>. Interpret your results.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load necessary package</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readr)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Read the data from GitHub</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>url <span class="ot">&lt;-</span> <span class="st">"https://raw.githubusercontent.com/danilofreire/qtm385/main/assignments/09-assignment/Rind_Bordia_JASP_1996.csv"</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>rind_data <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(url)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 89 Columns: 5
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
dbl (5): female, happyface, tip, xhappy, tipround

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># View the first few rows of the dataset</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(rind_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 5
  female happyface   tip xhappy tipround
   &lt;dbl&gt;     &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;    &lt;dbl&gt;
1      1         0  44.8      0       45
2      1         0  27.6      0       28
3      1         0  18.1      0       18
4      0         0   0        0        0
5      1         0  30.1      0       30
6      0         0  16.3      0       16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># View column names</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(rind_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "female"    "happyface" "tip"       "xhappy"    "tipround" </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load necessary packages</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readr)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'dplyr'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:stats':

    filter, lag</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union</code></pre>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Load and prepare the data</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>url <span class="ot">&lt;-</span> <span class="st">"https://raw.githubusercontent.com/danilofreire/qtm385/main/assignments/09-assignment/Rind_Bordia_JASP_1996.csv"</span></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>rind_data <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(url)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 89 Columns: 5</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
dbl (5): female, happyface, tip, xhappy, tipround

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Clean and rename variables</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> rind_data <span class="sc">%&gt;%</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">happyface =</span> <span class="fu">as.integer</span>(happyface),  <span class="co"># Treatment: 1 = happy face, 0 = no face</span></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">tip =</span> tip  <span class="co"># Outcome: tip percentage</span></span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute observed average treatment effect (ATE)</span></span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>obs_ATE <span class="ot">&lt;-</span> <span class="fu">mean</span>(data<span class="sc">$</span>tip[data<span class="sc">$</span>happyface <span class="sc">==</span> <span class="dv">1</span>], <span class="at">na.rm =</span> <span class="cn">TRUE</span>) <span class="sc">-</span></span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a>           <span class="fu">mean</span>(data<span class="sc">$</span>tip[data<span class="sc">$</span>happyface <span class="sc">==</span> <span class="dv">0</span>], <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Construct full schedule of potential outcomes under constant treatment effect</span></span>
<span id="cb14-13"><a href="#cb14-13" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb14-14"><a href="#cb14-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb14-15"><a href="#cb14-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">Y0 =</span> <span class="fu">ifelse</span>(happyface <span class="sc">==</span> <span class="dv">0</span>, tip, tip <span class="sc">-</span> obs_ATE),</span>
<span id="cb14-16"><a href="#cb14-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">Y1 =</span> <span class="fu">ifelse</span>(happyface <span class="sc">==</span> <span class="dv">1</span>, tip, tip <span class="sc">+</span> obs_ATE)</span>
<span id="cb14-17"><a href="#cb14-17" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb14-18"><a href="#cb14-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-19"><a href="#cb14-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute observed variance difference</span></span>
<span id="cb14-20"><a href="#cb14-20" aria-hidden="true" tabindex="-1"></a>obs_var_diff <span class="ot">&lt;-</span> <span class="fu">var</span>(data<span class="sc">$</span>Y1, <span class="at">na.rm =</span> <span class="cn">TRUE</span>) <span class="sc">-</span> <span class="fu">var</span>(data<span class="sc">$</span>Y0, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb14-21"><a href="#cb14-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-22"><a href="#cb14-22" aria-hidden="true" tabindex="-1"></a><span class="co"># Randomization inference to test Var(Y1) = Var(Y0)</span></span>
<span id="cb14-23"><a href="#cb14-23" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb14-24"><a href="#cb14-24" aria-hidden="true" tabindex="-1"></a>n_sims <span class="ot">&lt;-</span> <span class="dv">1000</span></span>
<span id="cb14-25"><a href="#cb14-25" aria-hidden="true" tabindex="-1"></a>var_diffs <span class="ot">&lt;-</span> <span class="fu">numeric</span>(n_sims)</span>
<span id="cb14-26"><a href="#cb14-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-27"><a href="#cb14-27" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>n_sims) {</span>
<span id="cb14-28"><a href="#cb14-28" aria-hidden="true" tabindex="-1"></a>  shuffled <span class="ot">&lt;-</span> <span class="fu">sample</span>(data<span class="sc">$</span>happyface)</span>
<span id="cb14-29"><a href="#cb14-29" aria-hidden="true" tabindex="-1"></a>  Y1_i <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(shuffled <span class="sc">==</span> <span class="dv">1</span>, data<span class="sc">$</span>tip, data<span class="sc">$</span>tip <span class="sc">+</span> obs_ATE)</span>
<span id="cb14-30"><a href="#cb14-30" aria-hidden="true" tabindex="-1"></a>  Y0_i <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(shuffled <span class="sc">==</span> <span class="dv">0</span>, data<span class="sc">$</span>tip, data<span class="sc">$</span>tip <span class="sc">-</span> obs_ATE)</span>
<span id="cb14-31"><a href="#cb14-31" aria-hidden="true" tabindex="-1"></a>  var_diffs[i] <span class="ot">&lt;-</span> <span class="fu">var</span>(Y1_i, <span class="at">na.rm =</span> <span class="cn">TRUE</span>) <span class="sc">-</span> <span class="fu">var</span>(Y0_i, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb14-32"><a href="#cb14-32" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb14-33"><a href="#cb14-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-34"><a href="#cb14-34" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate two-sided p-value</span></span>
<span id="cb14-35"><a href="#cb14-35" aria-hidden="true" tabindex="-1"></a>p_value <span class="ot">&lt;-</span> <span class="fu">mean</span>(<span class="fu">abs</span>(var_diffs) <span class="sc">&gt;=</span> <span class="fu">abs</span>(obs_var_diff))</span>
<span id="cb14-36"><a href="#cb14-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-37"><a href="#cb14-37" aria-hidden="true" tabindex="-1"></a><span class="co"># Output results</span></span>
<span id="cb14-38"><a href="#cb14-38" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Observed Variance Difference:"</span>, <span class="fu">round</span>(obs_var_diff, <span class="dv">4</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Observed Variance Difference: 0 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"P-value from Randomization Inference:"</span>, <span class="fu">round</span>(p_value, <span class="dv">4</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>P-value from Randomization Inference: 0.735 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot randomization distribution</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="fu">data.frame</span>(var_diffs), <span class="fu">aes</span>(<span class="at">x =</span> var_diffs)) <span class="sc">+</span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">30</span>, <span class="at">fill =</span> <span class="st">"skyblue"</span>, <span class="at">color =</span> <span class="st">"white"</span>) <span class="sc">+</span></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> obs_var_diff, <span class="at">color =</span> <span class="st">"red"</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>) <span class="sc">+</span></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Randomization Distribution of Variance Difference"</span>,</span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Variance Difference (Y1 - Y0)"</span>,</span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Frequency"</span></span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="09-assignment_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ol start="7" type="1">
<li>Write down a regression model that depicts the effect of the sex of the waitstaff, whether they write a happy face on the bill, and the interaction of these factors. To analyze how the sex of the waitstaff and the act of drawing a happy face on the bill influence tipping behavior, we can specify a linear regression model that includes both main effects and their interaction. The outcome variable is the tip percentage received by each server. The model includes a binary variable for server sex, where <em>Female</em> is coded as 1 for female servers and 0 for male servers, and a binary treatment variable <em>HappyFace</em>, coded as 1 if the server drew a happy face on the bill and 0 otherwise. Additionally, the model includes an interaction term between <em>Female</em> and <em>HappyFace</em> to capture whether the effect of drawing a happy face depends on the server’s sex.</li>
</ol>
<p>This specification allows us to interpret the coefficients as follows: the intercept represents the average tip for male servers who did not draw a happy face. The coefficient on <em>Female</em> captures the difference in tip percentage between female and male servers when no happy face is drawn, while the coefficient on <em>HappyFace</em> reflects the effect of drawing a happy face for male servers. The interaction term estimates the additional or differential effect of the happy face when the server is female. Together, this model provides a framework for assessing whether the happy face treatment is more or less effective depending on the gender of the waitstaff.</p>
<ol start="8" type="1">
<li>Estimate the regression model in question 07 and test the interaction between waitstaff sex and the happy face treatment. Is the interaction significant?</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load necessary package</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readr)</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Load the data</span></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>url <span class="ot">&lt;-</span> <span class="st">"https://raw.githubusercontent.com/danilofreire/qtm385/main/assignments/09-assignment/Rind_Bordia_JASP_1996.csv"</span></span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>rind_data <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(url)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 89 Columns: 5
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
dbl (5): female, happyface, tip, xhappy, tipround

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit regression model with interaction</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(tip <span class="sc">~</span> female <span class="sc">*</span> happyface, <span class="at">data =</span> rind_data)</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Display regression summary</span></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = tip ~ female * happyface, data = rind_data)

Residuals:
    Min      1Q  Median      3Q     Max 
-21.406  -5.726  -0.684   5.286  39.419 

Coefficients:
                 Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)        21.406      2.287   9.360 1.01e-14 ***
female              6.378      3.163   2.016   0.0469 *  
happyface          -3.630      3.163  -1.147   0.2544    
female:happyface    8.887      4.447   1.999   0.0488 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 10.48 on 85 degrees of freedom
Multiple R-squared:  0.2476,    Adjusted R-squared:  0.2211 
F-statistic: 9.325 on 3 and 85 DF,  p-value: 2.14e-05</code></pre>
</div>
</div>
<ol start="9" type="1">
<li>A large clinical trial (<span class="math inline">\(N=2000\)</span>) finds a statistically significant average treatment effect (ATE) of a new drug. The researchers decide to explore heterogeneity by splitting the sample into 10 pre-defined subgroups based on demographic characteristics (e.g., 5 age bins x 2 genders). They run separate analyses within each subgroup.</li>
</ol>
<ol type="a">
<li>If the treatment effect is truly homogeneous (the same for everyone), what is the approximate probability that at least one of the 10 subgroup analyses will yield a statistically significant result (at <span class="math inline">\(\alpha=0.05\)</span>) just by chance? Show your calculation. If the treatment effect is truly homogeneous across all individuals, the probability of finding a statistically significant effect in any given subgroup analysis purely by chance is 5%, or 0.05. Conversely, the probability of not finding a significant effect in one test is 1 – 0.05 = 0.95. Assuming the 10 subgroup tests are independent, the probability that none of them yield a statistically significant result is (0.95^{10} ).</li>
</ol>
<p>Therefore, the probability that <strong>at least one</strong> of the 10 subgroup analyses results in a false positive is (1 - 0.95^{10} = 1 - 0.5987 = 0.4013), or approximately <strong>40.13%</strong>. This means that even when the treatment effect is truly the same for everyone, there is about a 40% chance that the researchers will incorrectly detect a significant effect in at least one subgroup just by chance, illustrating the importance of adjusting for multiple comparisons.</p>
<ol start="2" type="a">
<li>If the researchers find significant effects in 2 subgroups and non-significant effects in the other 8, explain the pitfalls of concluding that the drug “only works” for those 2 subgroups. If researchers find statistically significant effects in 2 out of 10 subgroups, it is tempting to conclude that the drug “only works” for those two groups. However, this conclusion is problematic due to the <strong>multiple comparisons problem</strong>. When conducting multiple subgroup analyses, each at a significance level of (= 0.05), the likelihood of finding at least one false positive increases. As shown previously, if the treatment effect is actually the same across all groups, there is about a <strong>40% chance</strong> of finding at least one statistically significant result just by random variation.</li>
</ol>
<p>In this case, finding significant effects in <strong>2 out of 10 subgroups</strong> could simply be a product of chance. With 10 independent tests, the expected number of false positives under the null hypothesis is (10 = 0.5), and while observing 2 may seem notable, it still falls within the range of random fluctuation — especially if no correction for multiple testing (like Bonferroni or FDR) has been applied. Without formally testing whether these subgroup effects are significantly different from the others (e.g., through interaction terms in a regression), claiming that the drug “only works” for certain groups is statistically unjustified and risks overstating subgroup differences that may not be real.</p>
<ol start="10" type="1">
<li>Distinguish between treatment effect heterogeneity and confounding. Can controlling for a variable address both issues simultaneously? Please explain. <strong>Treatment effect heterogeneity</strong> and <strong>confounding</strong> are distinct concepts in causal inference, though they both involve relationships between variables and outcomes.</li>
</ol>
<p><strong>Treatment effect heterogeneity</strong> occurs when the effect of a treatment varies across subgroups of a population — for example, a drug may lower blood pressure more in older patients than in younger ones. It reflects genuine differences in how individuals respond to treatment and is often studied by interacting the treatment with covariates or estimating conditional average treatment effects (CATEs).</p>
<p><strong>Confounding</strong>, on the other hand, arises when an external variable influences both the treatment assignment and the outcome, creating a spurious association. For example, if healthier people are more likely to receive a treatment and also more likely to have better outcomes, the treatment may appear more effective than it truly is.</p>
<p><strong>Controlling for a variable</strong> can help with both issues, but in different ways. When used to adjust for confounding, controlling for a variable blocks a non-causal path, helping to isolate the true treatment effect. When investigating heterogeneity, controlling (or interacting) with a variable helps identify whether the treatment effect varies across levels of that variable. However, while the same covariate may sometimes serve both purposes, <strong>controlling for it does not automatically solve both problems</strong> — it depends on whether the variable is a confounder or a moderator of treatment effect.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>